### ISSUE TITLE
ключ для отслеживания не должен быть порядковым номером 

### ISSUE THREAD

**Issue by tamazyanarsen** [AnastasiiaShirova/todo-project-work#14]
https://github.com/AnastasiiaShirova/todo-project-work/blob/04ab4c164e2e3e1310d2a181802e581b1272b934/src/app/modules/todo/components/todo-list/todo-list.component.html#L3

почитай в документации ангуляра, почему не стоит использовать порядковый номер элемента в качестве ключа в списке для рендерига

**Comment by AnastasiiaShirova** [comment]
Исправила

**Comment by AnastasiiaShirova** [comment]
Исправила
